
public enum PageTabIndex
{
    HOME_PAGE,
    RECORDS_PAGE,
    CHAT_PAGE,
    REPORT_PAGE,
    LOGIN_PAGE,
    VIEW_REPORTS_PAGE,
    VIEW_TIMETABLE_PAGE,
    CANTEEN_PAGE,
    VIEW_STUDENT_LOGS_PAGE,
    ADD_STUDENT_LOGS_PAGE,
    FORUM_PAGE,
}
